### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by anouarcharif** [qligier/angular4-events#1]
Hello,

I tried to use your plugin, but it's not working ...

ERROR in Error: Error encountered resolving symbol values statically. Could not resolve angular4-events relative to

**Comment by qligier** [comment]
I can't reproduce that. What version of angular and typescript are you using? Could you provider your _app.module.ts_ and the file(s) in which you are importing _EventsModule_?

**Comment by anouarcharif** [comment]
Hello,

When i try to import the definition for my app.module like that:

import { EventsModule } from 'angular4-events';

Cannot find module 'angular4-events'.

Hello,

When i try to import the definition for my app.module like that:

import { EventsModule } from 'angular4-events';

Cannot find module 'angular4-events'.

**Comment by anouarcharif** [comment]
Here's my env:

@angular/cli: 1.4.9
node: 8.6.0
os: darwin x64
@angular/animations: 4.4.6
@angular/common: 4.4.6
@angular/compiler: 4.4.6
@angular/core: 4.4.6
@angular/forms: 4.4.6
@angular/http: 4.4.6
@angular/platform-browser: 4.4.6
@angular/platform-browser-dynamic: 4.4.6
@angular/router: 4.4.6
@angular/cli: 1.4.9
@angular/compiler-cli: 4.4.6
@angular/language-service: 4.4.6
typescript: 2.3.4

**Comment by anouarcharif** [comment]
```
@angular/cli: 1.4.9
node: 8.6.0
os: darwin x64
@angular/animations: 4.4.6
@angular/common: 4.4.6
@angular/compiler: 4.4.6
@angular/core: 4.4.6
@angular/forms: 4.4.6
@angular/http: 4.4.6
@angular/platform-browser: 4.4.6
@angular/platform-browser-dynamic: 4.4.6
@angular/router: 4.4.6
@angular/cli: 1.4.9
@angular/compiler-cli: 4.4.6
@angular/language-service: 4.4.6
typescript: 2.3.4
```

**Comment by qligier** [comment]
Have you donwloaded the module (`npm install --save angular4-events`)? If you run `npm list --depth=0`, it should appear as "_angular4-events@4.0.1_".

**Comment by qligier** [comment]
I just tried to create a test app:
```
ng new TestApp
cd TestApp
npm install --save angular4-events
```
Adding the following lines to _src/app/app.module.ts_ does not throw any error:
```js
import { EventsModule } from 'angular4-events';
...
@NgModule({
	imports: [
		...
		EventsModule.forRoot()
	]
})
```

Could you try to do the same?

**Comment by anouarcharif** [comment]
Hello,

Here what i do:

npm install --save angular4-events
`
+ angular4-events@4.0.1
updated 1 package in 14.422s
`
Then when i try to import in my app.module like this :
import { EventsModule } from 'angular4-events';

and 

@NgModule({
	imports: [
		...
		EventsModule.forRoot()
	]
})

**Comment by anouarcharif** [comment]
I  did the same thing again, and now it work 🗡

**Comment by qligier** [comment]
Great, I'm glad it works!
