### ISSUE TITLE
angular 6 prod build error

### ISSUE THREAD

**Issue by n7229** [qligier/angular4-events#5]
ERROR in ../angular4-events/esm/src/angular4-events.module.ts(4,2): Error during template compile of 'EventsModule'
  Function calls are not supported in decorators but 'ɵmakeDecorator' was called in 'NgModule'
    'NgModule' calls 'ɵmakeDecorator'.

node_modules/angular4-events/node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.

**Comment by qligier** [comment]
Hey,
Can you try with the new version (`npm install --save angular4-events@5.0.1`)? It should fix issues with Angular 6 but I still haven't had time to upgrade my own projects, so feedback would be appreciated.

**Comment by n7229** [comment]
this is a good one to migrate 
https://alligator.io/angular/angular-6/

**Comment by qligier** [comment]
Closing this issue as it should have been fixed with v5.0.1 update.
