### ISSUE TITLE
angular 5 builds failing 5.0.1

### ISSUE THREAD

**Issue by n7229** [qligier/angular4-events#6]
ERROR in ../angular4-events/esm/src/angular4-events.module.ts(4,2): Error during template compile of 'EventsModule'
  Function calls are not supported in decorators but 'ɵmakeDecorator' was called in 'NgModule'
    'NgModule' calls 'ɵmakeDecorator'.
node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.
node_modules/angular4-events/node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.

**Comment by qligier** [comment]
Seems like v5.0.1 is only for Angular 6, please downgrade to v5.0.0 with Angular 5. I'll update the doc.
Isn't it the same error previously reported for v5.0.0 and Angular 6?

**Comment by qligier** [comment]
Closing this issue, the doc has been updated.
